pipeline:
  name: create_github_repo
  identifier: create_github_repo
  projectIdentifier: shashank_idp_test
  orgIdentifier: shashank
  tags: {}
  stages:
    - stage:
        name: create_github_repo
        identifier: create_github_repo
        description: ""
        type: IDP
        spec:
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: CreateRepo
                  name: Create_repo_github
                  identifier: Create_repo_github
                  spec:
                    connectorType: Github
                    connectorRef: account.Shashank_github_connector
                    organization: <+input>
                    repository: newrepo_idp_automation
                    repoType: public
                    description: automatically created through IDP
                    defaultBranch: main
                    personalAccount: false
        tags: {}
